export const memeWarriors = [
  {
    id: "pepe",
    name: "Pepe the Frog",
    image: "/placeholder-vv6qc.png",
    description: "The original meme frog with unpredictable market moves and legendary status in the crypto world.",
    class: "Amphibian Trader",
    power: 9500,
    level: 99,
    rarity: "Legendary",
    wins: 420,
    losses: 69,
    abilities: ["Market Manipulation", "Pump and Dump", "FOMO Generation"],
    background:
      "Born in a humble comic in 2005, Pepe rose to become the most recognized meme in crypto. His unpredictable nature mirrors the volatile markets he thrives in.",
  },
  {
    id: "doge",
    name: "Doge",
    image: "/placeholder-ar8q4.png",
    description: "The Shiba Inu that started as a joke and became a multi-billion dollar cryptocurrency.",
    class: "Meme Coin Oracle",
    power: 8900,
    level: 95,
    rarity: "Legendary",
    wins: 380,
    losses: 75,
    abilities: ["Much Wow", "Very Gains", "Celebrity Endorsement"],
    background:
      "A simple Shiba Inu photograph became the face of one of the most valuable meme coins in history. Doge's innocent appearance masks a powerful market influence.",
  },
  {
    id: "wojak",
    name: "Wojak",
    image: "/wojak-meme.png",
    description: "The emotional trader experiencing all the highs and lows of the market.",
    class: "Sentiment Analyst",
    power: 7200,
    level: 85,
    rarity: "Epic",
    wins: 210,
    losses: 190,
    abilities: ["Emotional Damage", "Capitulation", "Buy High Sell Low"],
    background:
      "Wojak represents the emotional rollercoaster of trading. His many expressions have become a language for expressing market sentiment across the globe.",
  },
  {
    id: "chad",
    name: "Gigachad",
    image: "/placeholder-awn07.png",
    description: "The ultimate alpha trader who never doubts his strategy and always buys the dip.",
    class: "Alpha Strategist",
    power: 9200,
    level: 97,
    rarity: "Legendary",
    wins: 450,
    losses: 50,
    abilities: ["Diamond Hands", "FUD Immunity", "Alpha Generation"],
    background:
      "The embodiment of trading confidence, Gigachad never questions his decisions. His unwavering belief in his strategy has led to legendary status in the trading community.",
  },
  {
    id: "distracted",
    name: "Distracted Boyfriend",
    image: "/distracted-boyfriend.png",
    description: "Always chasing the next hot token while neglecting his current investments.",
    class: "Trend Chaser",
    power: 6800,
    level: 75,
    rarity: "Rare",
    wins: 180,
    losses: 220,
    abilities: ["FOMO Inducement", "Attention Diversion", "Portfolio Rotation"],
    background:
      "The Distracted Boyfriend is always looking for the next big thing, often at the expense of his current holdings. His wandering eye has both made and lost fortunes.",
  },
  {
    id: "pikachu",
    name: "Surprised Pikachu",
    image: "/surprised-pikachu-meme.png",
    description: "Perpetually shocked by market movements despite them being entirely predictable.",
    class: "Shock Absorber",
    power: 7500,
    level: 80,
    rarity: "Epic",
    wins: 250,
    losses: 150,
    abilities: ["Feigned Surprise", "Volatility Resistance", "Meme Lightning"],
    background:
      "Despite being in the market for years, Surprised Pikachu is always shocked by the same patterns repeating. His constant surprise has become his greatest strength.",
  },
  {
    id: "moonmoon",
    name: "Moon Moon",
    image: "/placeholder-u7mgy.png",
    description: "The derpy wolf who's always howling about tokens going to the moon.",
    class: "Lunar Prophet",
    power: 6500,
    level: 70,
    rarity: "Rare",
    wins: 170,
    losses: 230,
    abilities: ["Howl at the Moon", "Derp Strategy", "Pack Mentality"],
    background:
      "Moon Moon is the eternal optimist, always believing every token is going to the moon. His enthusiasm is infectious, even if his predictions aren't always accurate.",
  },
  {
    id: "thisisfineDog",
    name: "This is Fine Dog",
    image: "/this-is-fine-dog.png",
    description: "Remains calm and collected even as the market burns around him.",
    class: "Stoic Hodler",
    power: 8000,
    level: 88,
    rarity: "Epic",
    wins: 300,
    losses: 100,
    abilities: ["Crisis Immunity", "Zen State", "Fire Resistance"],
    background:
      "In the midst of market chaos, This is Fine Dog maintains perfect composure. His ability to stay calm in a crisis has saved his portfolio countless times.",
  },
]

export const leaderboardData = [
  {
    rank: 1,
    player: "CryptoKing",
    avatar: "/placeholder-snzci.png",
    warrior: "Pepe the Frog",
    wins: 1287,
    losses: 213,
    winRate: "85.8%",
    earnings: "$1,245,678",
  },
  {
    rank: 2,
    player: "MoonGirl",
    avatar: "/placeholder.svg?height=50&width=50&query=moon girl avatar",
    warrior: "Doge",
    wins: 1156,
    losses: 244,
    winRate: "82.6%",
    earnings: "$987,654",
  },
  {
    rank: 3,
    player: "DiamondHands",
    avatar: "/placeholder.svg?height=50&width=50&query=diamond hands avatar",
    warrior: "Gigachad",
    wins: 1089,
    losses: 311,
    winRate: "77.8%",
    earnings: "$876,543",
  },
  {
    rank: 4,
    player: "Hodlr4Life",
    avatar: "/placeholder.svg?height=50&width=50&query=hodler avatar",
    warrior: "This is Fine Dog",
    wins: 978,
    losses: 322,
    winRate: "75.2%",
    earnings: "$765,432",
  },
  {
    rank: 5,
    player: "TradingQueen",
    avatar: "/placeholder.svg?height=50&width=50&query=trading queen avatar",
    warrior: "Surprised Pikachu",
    wins: 945,
    losses: 355,
    winRate: "72.7%",
    earnings: "$654,321",
  },
  {
    rank: 6,
    player: "MemeGod",
    avatar: "/placeholder.svg?height=50&width=50&query=meme god avatar",
    warrior: "Wojak",
    wins: 901,
    losses: 399,
    winRate: "69.3%",
    earnings: "$543,210",
  },
  {
    rank: 7,
    player: "CoinCollector",
    avatar: "/placeholder.svg?height=50&width=50&query=coin collector avatar",
    warrior: "Distracted Boyfriend",
    wins: 876,
    losses: 424,
    winRate: "67.4%",
    earnings: "$432,109",
  },
  {
    rank: 8,
    player: "SatoshisFriend",
    avatar: "/placeholder.svg?height=50&width=50&query=satoshi friend avatar",
    warrior: "Moon Moon",
    wins: 854,
    losses: 446,
    winRate: "65.7%",
    earnings: "$321,098",
  },
  {
    rank: 9,
    player: "BlockchainBaron",
    avatar: "/placeholder.svg?height=50&width=50&query=blockchain baron avatar",
    warrior: "Pepe the Frog",
    wins: 832,
    losses: 468,
    winRate: "64.0%",
    earnings: "$210,987",
  },
  {
    rank: 10,
    player: "TokenTitan",
    avatar: "/placeholder.svg?height=50&width=50&query=token titan avatar",
    warrior: "Gigachad",
    wins: 810,
    losses: 490,
    winRate: "62.3%",
    earnings: "$109,876",
  },
]

export const questsData = [
  {
    id: "daily-battles",
    title: "Daily Battles",
    description: "Complete 5 battles in a single day",
    reward: "500 $MEME",
    difficulty: "Easy",
    icon: "/placeholder.svg?height=50&width=50&query=battle icon",
    progress: 60,
    timeLeft: "14 hours",
  },
  {
    id: "win-streak",
    title: "Win Streak",
    description: "Win 10 battles in a row",
    reward: "1,000 $MEME",
    difficulty: "Medium",
    icon: "/placeholder.svg?height=50&width=50&query=win streak icon",
    progress: 40,
    timeLeft: "Ongoing",
  },
  {
    id: "legendary-hunt",
    title: "Legendary Hunt",
    description: "Defeat a Legendary warrior in battle",
    reward: "2,000 $MEME + Rare Item",
    difficulty: "Hard",
    icon: "/placeholder.svg?height=50&width=50&query=legendary hunt icon",
    progress: 0,
    timeLeft: "Ongoing",
  },
  {
    id: "token-collector",
    title: "Token Collector",
    description: "Collect 5,000 $MEME tokens",
    reward: "Exclusive Warrior Skin",
    difficulty: "Medium",
    icon: "/placeholder.svg?height=50&width=50&query=token collector icon",
    progress: 75,
    timeLeft: "Ongoing",
  },
  {
    id: "social-butterfly",
    title: "Social Butterfly",
    description: "Refer 3 friends to join MemeWars",
    reward: "1,500 $MEME + Exclusive Title",
    difficulty: "Easy",
    icon: "/placeholder.svg?height=50&width=50&query=social butterfly icon",
    progress: 33,
    timeLeft: "Ongoing",
  },
  {
    id: "tournament-champion",
    title: "Tournament Champion",
    description: "Reach the finals in a weekly tournament",
    reward: "5,000 $MEME + Legendary Item",
    difficulty: "Hard",
    icon: "/placeholder.svg?height=50&width=50&query=tournament champion icon",
    progress: 10,
    timeLeft: "5 days",
  },
]

export const roadmapData = [
  {
    phase: "Phase 1",
    title: "Genesis",
    status: "Completed",
    items: [
      { title: "Concept Development", completed: true },
      { title: "Team Formation", completed: true },
      { title: "Initial Funding", completed: true },
      { title: "Website Launch", completed: true },
      { title: "Community Building", completed: true },
    ],
    description:
      "The birth of MemeWars, where the concept was developed, the core team was formed, and initial funding was secured. The website was launched and the community started to grow.",
  },
  {
    phase: "Phase 2",
    title: "Alpha Release",
    status: "In Progress",
    items: [
      { title: "Warrior NFT Creation", completed: true },
      { title: "Basic Battle Mechanics", completed: true },
      { title: "Alpha Testing", completed: true },
      { title: "Community Feedback", completed: true },
      { title: "Tokenomics Design", completed: false },
    ],
    description:
      "The first playable version of MemeWars, featuring the creation of Warrior NFTs, basic battle mechanics, and initial testing with a select group of community members.",
  },
  {
    phase: "Phase 3",
    title: "Beta Launch",
    status: "Upcoming",
    items: [
      { title: "$MEME Token Launch", completed: false },
      { title: "Advanced Battle System", completed: false },
      { title: "Marketplace Integration", completed: false },
      { title: "Leaderboards & Rewards", completed: false },
      { title: "Mobile Optimization", completed: false },
    ],
    description:
      "The public beta launch, introducing the $MEME token, an advanced battle system with more strategic options, a marketplace for trading warriors and items, and competitive leaderboards with rewards.",
  },
  {
    phase: "Phase 4",
    title: "Expansion",
    status: "Future",
    items: [
      { title: "Tournament System", completed: false },
      { title: "Guild Wars", completed: false },
      { title: "Cross-Chain Integration", completed: false },
      { title: "Mobile App Release", completed: false },
      { title: "Partnerships & Collabs", completed: false },
    ],
    description:
      "Expanding the MemeWars ecosystem with tournaments, guild wars for team-based competition, cross-chain integration for broader accessibility, a dedicated mobile app, and strategic partnerships with other projects and influencers.",
  },
  {
    phase: "Phase 5",
    title: "Metaverse",
    status: "Future",
    items: [
      { title: "MemeWars Metaverse", completed: false },
      { title: "Virtual Land Sales", completed: false },
      { title: "3D Warrior Avatars", completed: false },
      { title: "Social Hubs", completed: false },
      { title: "Governance DAO", completed: false },
    ],
    description:
      "The ultimate vision for MemeWars, featuring a dedicated metaverse where players can own virtual land, use 3D avatars of their warriors, socialize in dedicated hubs, and participate in governance through a DAO structure.",
  },
]
