// MemeWarriors data
export const memeWarriors = [
  {
    id: "pepe",
    name: "Pepe the Frog",
    image: "/images/warriors/pepe.png",
    rarity: "Legendary",
    level: 42,
    power: 9001,
    wins: 320,
    losses: 80,
    description: "The original meme frog with devastating attack power and special abilities.",
    abilities: ["Rare Pepe Blast", "Feels Good Man", "Sadge Aura"],
    stats: {
      attack: 95,
      defense: 85,
      speed: 75,
      health: 90,
      special: 98,
    },
  },
  {
    id: "doge",
    name: "Doge Warrior",
    image: "/images/warriors/doge.png",
    rarity: "Epic",
    level: 38,
    power: 8500,
    wins: 280,
    losses: 120,
    description: "Much fight. Very strong. Wow.",
    abilities: ["Such Attack", "Many Defense", "Wow Blast"],
    stats: {
      attack: 88,
      defense: 90,
      speed: 92,
      health: 85,
      special: 87,
    },
  },
  {
    id: "wojak",
    name: "Wojak",
    image: "/images/warriors/wojak.png",
    rarity: "Rare",
    level: 35,
    power: 7200,
    wins: 210,
    losses: 140,
    description: "Feels the pain of battle but channels it into powerful attacks.",
    abilities: ["Feel Attack", "Pain Endurance", "Doomer Blast"],
    stats: {
      attack: 80,
      defense: 75,
      speed: 70,
      health: 95,
      special: 85,
    },
  },
  {
    id: "chad",
    name: "Gigachad",
    image: "/images/warriors/chad.png",
    rarity: "Epic",
    level: 40,
    power: 8800,
    wins: 300,
    losses: 50,
    description: "The ultimate physical specimen with unmatched strength.",
    abilities: ["Chad Smash", "Flex Defense", "Sigma Aura"],
    stats: {
      attack: 98,
      defense: 92,
      speed: 75,
      health: 95,
      special: 80,
    },
  },
  {
    id: "distracted",
    name: "Distracted Boyfriend",
    image: "/images/warriors/distracted.png",
    rarity: "Rare",
    level: 32,
    power: 7000,
    wins: 180,
    losses: 160,
    description: "Always looking for new opportunities in battle.",
    abilities: ["Wandering Eye", "Double Take", "Girlfriend's Rage"],
    stats: {
      attack: 75,
      defense: 70,
      speed: 90,
      health: 80,
      special: 85,
    },
  },
  {
    id: "pikachu",
    name: "Surprised Pikachu",
    image: "/images/warriors/pikachu.png",
    rarity: "Epic",
    level: 37,
    power: 8300,
    wins: 250,
    losses: 130,
    description: "Shocks opponents with surprising attack power.",
    abilities: ["Shock Face", "Surprise Attack", "Viral Blast"],
    stats: {
      attack: 85,
      defense: 80,
      speed: 95,
      health: 82,
      special: 90,
    },
  },
  {
    id: "moonmoon",
    name: "Moon Moon",
    image: "/images/warriors/moonmoon.png",
    rarity: "Common",
    level: 28,
    power: 6500,
    wins: 150,
    losses: 200,
    description: "Not the brightest warrior, but makes up for it with enthusiasm.",
    abilities: ["Confused Attack", "Accidental Defense", "Derp Charge"],
    stats: {
      attack: 70,
      defense: 65,
      speed: 85,
      health: 75,
      special: 70,
    },
  },
  {
    id: "thisisfineDog",
    name: "This is Fine Dog",
    image: "/images/warriors/thisisfineDog.png",
    rarity: "Epic",
    level: 39,
    power: 8600,
    wins: 270,
    losses: 110,
    description: "Remains calm under pressure, even when surrounded by flames.",
    abilities: ["Flame Resistance", "Calm Mind", "Fine Blast"],
    stats: {
      attack: 82,
      defense: 95,
      speed: 70,
      health: 90,
      special: 88,
    },
  },
]

// Leaderboard data
export const leaderboardData = [
  {
    rank: 1,
    username: "MemeKing420",
    avatar: "/images/avatars/player1.png",
    level: 50,
    wins: 520,
    losses: 180,
    winRate: 74.3,
    seasonPoints: 12500,
  },
  {
    rank: 2,
    username: "DogeWarrior",
    avatar: "/images/avatars/player2.png",
    level: 48,
    wins: 490,
    losses: 210,
    winRate: 70.0,
    seasonPoints: 11800,
  },
  {
    rank: 3,
    username: "PepeHands",
    avatar: "/images/avatars/player3.png",
    level: 47,
    wins: 475,
    losses: 225,
    winRate: 67.9,
    seasonPoints: 11200,
  },
  {
    rank: 4,
    username: "StonksOnly",
    avatar: "/images/avatars/player4.png",
    level: 46,
    wins: 460,
    losses: 240,
    winRate: 65.7,
    seasonPoints: 10800,
  },
  {
    rank: 5,
    username: "WojakFeels",
    avatar: "/images/avatars/player5.png",
    level: 45,
    wins: 445,
    losses: 255,
    winRate: 63.6,
    seasonPoints: 10500,
  },
  {
    rank: 6,
    username: "ChadEnjoyer",
    avatar: "/images/avatars/player6.png",
    level: 44,
    wins: 430,
    losses: 270,
    winRate: 61.4,
    seasonPoints: 10200,
  },
  {
    rank: 7,
    username: "MoonMoonLover",
    avatar: "/images/avatars/player7.png",
    level: 43,
    wins: 415,
    losses: 285,
    winRate: 59.3,
    seasonPoints: 9900,
  },
  {
    rank: 8,
    username: "ThisIsFineGuy",
    avatar: "/images/avatars/player8.png",
    level: 42,
    wins: 400,
    losses: 300,
    winRate: 57.1,
    seasonPoints: 9600,
  },
  {
    rank: 9,
    username: "SurprisedMemer",
    avatar: "/images/avatars/player9.png",
    level: 41,
    wins: 385,
    losses: 315,
    winRate: 55.0,
    seasonPoints: 9300,
  },
  {
    rank: 10,
    username: "DistractedGamer",
    avatar: "/images/avatars/player10.png",
    level: 40,
    wins: 370,
    losses: 330,
    winRate: 52.9,
    seasonPoints: 9000,
  },
]

// Quests data
export const questsData = [
  {
    id: 1,
    title: "Social Media Warrior",
    description: "Share your MemeWars profile on Twitter and tag 3 friends",
    reward: {
      xp: 100,
      coins: 50,
      items: ["Common Loot Box"],
    },
    difficulty: "Easy",
    timeLimit: "24 hours",
    completions: 1250,
    icon: "/images/quest-icon-1.png",
    status: "available",
  },
  {
    id: 2,
    title: "Meme Creator",
    description: "Create and share an original meme featuring your MemeWarrior",
    reward: {
      xp: 200,
      coins: 100,
      items: ["Rare Loot Box"],
    },
    difficulty: "Medium",
    timeLimit: "48 hours",
    completions: 850,
    icon: "/images/quest-icon-2.png",
    status: "available",
  },
  {
    id: 3,
    title: "Discord Champion",
    description: "Join the official Discord server and participate in a community event",
    reward: {
      xp: 150,
      coins: 75,
      items: ["Discord Badge"],
    },
    difficulty: "Easy",
    timeLimit: "72 hours",
    completions: 2100,
    icon: "/images/quest-icon-3.png",
    status: "available",
  },
  {
    id: 4,
    title: "Referral Master",
    description: "Invite 5 new players to join MemeWars using your referral code",
    reward: {
      xp: 500,
      coins: 250,
      items: ["Epic Loot Box", "Referral Badge"],
    },
    difficulty: "Hard",
    timeLimit: "7 days",
    completions: 320,
    icon: "/images/quest-icon-4.png",
    status: "available",
  },
  {
    id: 5,
    title: "Content Creator",
    description: "Create a YouTube video or Twitch stream featuring MemeWars gameplay",
    reward: {
      xp: 1000,
      coins: 500,
      items: ["Legendary Loot Box", "Creator Badge"],
    },
    difficulty: "Very Hard",
    timeLimit: "14 days",
    completions: 75,
    icon: "/images/quest-icon-5.png",
    status: "available",
  },
  {
    id: 6,
    title: "Community Contributor",
    description: "Submit feedback or suggestions that get implemented in the game",
    reward: {
      xp: 300,
      coins: 150,
      items: ["Contributor Badge", "Rare Loot Box"],
    },
    difficulty: "Medium",
    timeLimit: "Ongoing",
    completions: 430,
    icon: "/images/quest-icon-6.png",
    status: "available",
  },
]
